# Generated by Django 3.2.16 on 2023-06-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_id', models.CharField(max_length=256)),
                ('application_id', models.CharField(max_length=256)),
                ('collector_id', models.CharField(max_length=256)),
                ('external_reference', models.CharField(max_length=256)),
                ('init_point', models.CharField(max_length=256)),
                ('date_created', models.CharField(max_length=256)),
                ('last_modified', models.CharField(max_length=256)),
                ('reason', models.CharField(max_length=256)),
                ('frequency', models.IntegerField()),
                ('frequency_type', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10)),
                ('repetitions', models.IntegerField()),
                ('billing_day', models.IntegerField()),
                ('billing_day_proportional', models.BooleanField(default=True)),
                ('free_trial_frequency', models.IntegerField()),
                ('free_trial_frequency_type', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_id', models.CharField(max_length=3)),
                ('payment_methods_allowed', models.JSONField(default=dict)),
                ('back_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('external_reference', models.CharField(max_length=256)),
                ('preapproval_plan_id', models.CharField(max_length=256)),
                ('init_point', models.URLField()),
                ('back_url', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=20)),
                ('payer_id', models.CharField(max_length=256)),
                ('card_id', models.CharField(max_length=256)),
                ('payment_method_id', models.CharField(max_length=256)),
                ('next_payment_date', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='tiers.tier')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
