# Generated by Django 3.2.16 on 2023-06-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tier_creator', to='user.useraccount'),
            preserve_default=False,
        ),
    ]
