# Generated by Django 3.2.16 on 2023-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_auto_20230608_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='transaction_amount_proportional',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
