# Generated by Django 3.2.16 on 2023-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_tier_transaction_amount_proportional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='external_reference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='free_trial_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='free_trial_frequency_type',
            field=models.CharField(blank=True, choices=[('months', 'Months')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='init_point',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
