# Generated by Django 3.2.16 on 2023-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0005_auto_20230608_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='transaction_amount_proportional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
