# Generated by Django 3.2.16 on 2023-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0006_alter_tier_transaction_amount_proportional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('highlight', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tier',
            name='short_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AddField(
            model_name='tier',
            name='features',
            field=models.ManyToManyField(to='tiers.Features'),
        ),
    ]
