# Generated by Django 3.2.16 on 2023-06-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0007_auto_20230608_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
