# Generated by Django 3.2.16 on 2023-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0009_alter_tier_payment_methods_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='tier',
            name='mostPopular',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
