# Generated by Django 3.2.16 on 2023-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0010_auto_20230608_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='marketplace/courses/tiers/media'),
            preserve_default=False,
        ),
    ]
