# Generated by Django 3.2.16 on 2023-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0011_tier_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='vendor',
            field=models.EmailField(max_length=256),
        ),
    ]
