# Generated by Django 3.2.16 on 2023-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0015_alter_subscription_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
