# Generated by Django 3.2.16 on 2023-06-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
