# Generated by Django 3.2.16 on 2023-06-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0011_tier_thumbnail'),
        ('courses', '0009_alter_episode_content'),
        ('cart', '0005_cartitem_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.tier'),
        ),
    ]
