# Generated by Django 3.2.16 on 2023-06-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230608_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='banner',
            field=models.ImageField(blank=True, default='media/users/user_default_bg.png', null=True, upload_to='media/users/pictures/', verbose_name='Picture'),
        ),
    ]
