# Generated by Django 3.2.16 on 2023-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='banner',
            field=models.ImageField(blank=True, default='media/users/user_default_bg.jpg', null=True, upload_to='media/users/pictures/', verbose_name='Banner'),
        ),
    ]
