# Generated by Django 3.2.16 on 2023-06-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_comments', to='courses.episode'),
        ),
    ]
