# Generated by Django 3.2.16 on 2023-06-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_comment_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
