# Generated by Django 3.2.16 on 2023-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20230607_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='question_answers', to='courses.Answer'),
        ),
    ]
