# Generated by Django 3.2.16 on 2023-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_episode_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
